### ISSUE TITLE
set up CI and CD

### ISSUE THREAD

**Issue by smtheard** [smtheard/ShowTracker#9]
set up should run tests and then deploy 100% automated on merges to master after v0.1 is live.

**Comment by Toltar** [comment]
For CI and CD, might I suggest adding a git flow branching strategy.

**Comment by smtheard** [comment]
I will consider it down the line, right now I prefer to have just master as my production branch since versioning does not matter in a web app environment and I do not have to tag releases.

**Comment by smtheard** [comment]
peeled continuous deployment into an issue by itself #58

**Comment by Toltar** [comment]
@smtheard 👍 Great
